const CONFIG = {
    SERVER_URL: 'https://votre-base-donnees.com',
    CURRENCY: 'Gdes',
    GAMING_RULES: {
        BORLETTE: { lot1: 60, lot2: 20, lot3: 10 },
        LOTTO3: 500,
        LOTTO4: 1000,
        LOTTO5: 5000,
        MARIAGE: 1000,
        AUTO_MARRIAGE: 1000,
        AUTO_LOTTO4: 1000,
        AUTO_LOTTO5: 5000
    },
    DRAWS: [
        { id: 'flo_matin', name: 'Florida Matin', time: '13:30', color: 'var(--florida)' },
        { id: 'flo_soir', name: 'Florida Soir', time: '21:50', color: 'var(--florida)' },
        { id: 'ny_matin', name: 'New York Matin', time: '14:30', color: 'var(--newyork)' },
        { id: 'ny_soir', name: 'New York Soir', time: '20:00', color: 'var(--newyork)' },
        { id: 'ga_matin', name: 'Georgia Matin', time: '12:30', color: 'var(--georgia)' },
        { id: 'ga_soir', name: 'Georgia Soir', time: '19:00', color: 'var(--georgia)' },
        { id: 'tx_matin', name: 'Texas Matin', time: '11:30', color: 'var(--texas)' },
        { id: 'tx_soir', name: 'Texas Soir', time: '18:30', color: 'var(--texas)' },
        { id: 'tn_matin', name: 'Tunisia Matin', time: '10:00', color: 'var(--tunisia)' },
        { id: 'tn_soir', name: 'Tunisia Soir', time: '17:00', color: 'var(--tunisia)' }
    ]
};

let APP_STATE = {
    selectedDraw: 'flo_matin',
    selectedDraws: ['flo_matin'],
    multiDrawMode: false,
    selectedGame: 'borlette',
    currentCart: [],
    lastResults: null,
    ticketsHistory: JSON.parse(localStorage.getItem('lotato_tickets')) || [],
    lotto3Options: [false, false, false], // Modifié: toutes désélectionnées par défaut
    lotto4Options: [false, false, false], // Modifié: toutes désélectionnées par défaut
    lotto5Options: [false, false, false], // Modifié: toutes désélectionnées par défaut
    showNumericChips: false,
    showLottoGames: false,
    showSpecialGames: false,
    currentTab: 'home'
};

const SpecialGames = {
    generateBOBets(amount) {
        const bets = [];
        for (let i = 0; i < 100; i++) {
            const num = i.toString().padStart(2, '0');
            if (num[0] === num[1]) {
                bets.push({
                    id: Date.now() + Math.random(),
                    game: 'borlette',
                    number: num,
                    cleanNumber: num,
                    amount: amount,
                    drawId: APP_STATE.selectedDraw,
                    timestamp: new Date().toISOString(),
                    isAutoGenerated: true,
                    specialType: 'BO'
                });
            }
        }
        return bets;
    },

    generateNBets(digit, amount) {
        const bets = [];
        for (let i = 0; i < 100; i++) {
            const num = i.toString().padStart(2, '0');
            if (num[1] === digit.toString()) {
                bets.push({
                    id: Date.now() + Math.random(),
                    game: 'borlette',
                    number: num,
                    cleanNumber: num,
                    amount: amount,
                    drawId: APP_STATE.selectedDraw,
                    timestamp: new Date().toISOString(),
                    isAutoGenerated: true,
                    specialType: `N${digit}`
                });
            }
        }
        return bets;
    },

    generateGRAPBets(amount) {
        const bets = [];
        for (let i = 0; i < 10; i++) {
            const num = i.toString().repeat(3);
            bets.push({
                id: Date.now() + Math.random(),
                game: 'lotto3',
                number: num,
                cleanNumber: num,
                amount: amount,
                drawId: APP_STATE.selectedDraw,
                timestamp: new Date().toISOString(),
                isAutoGenerated: true,
                specialType: 'GRAP'
            });
        }
        return bets;
    }
};

function setupInputAutoMove() {
    const numInput = document.getElementById('num-input');
    const amtInput = document.getElementById('amt-input');
    
    numInput.addEventListener('input', function(e) {
        const game = APP_STATE.selectedGame;
        let maxLength = 5;
        
        switch(game) {
            case 'borlette': maxLength = 2; break;
            case 'lotto3': maxLength = 3; break;
            case 'lotto4': maxLength = 4; break;
            case 'lotto5': maxLength = 5; break;
            case 'mariage': maxLength = 4; break;
            case 'auto_marriage': maxLength = 0; break;
            case 'auto_lotto4': maxLength = 0; break;
            case 'auto_lotto5': maxLength = 0; break;
            case 'bo': maxLength = 0; break;
            case 'grap': maxLength = 0; break;
        }
        
        if (game.startsWith('n')) {
            maxLength = 0;
        }
        
        if (this.value.length >= maxLength && maxLength > 0) {
            amtInput.focus();
            amtInput.select();
        }
        
        if (game === 'lotto4' && this.value.length === 4) {
            this.value = this.value.replace(/(\d{2})(\d{2})/, '$1-$2');
        } else if (game === 'lotto5' && this.value.length === 5) {
            this.value = this.value.replace(/(\d{3})(\d{2})/, '$1-$2');
        } else if (game === 'mariage' && this.value.length === 4) {
            this.value = this.value.replace(/(\d{2})(\d{2})/, '$1&$2');
        }
    });
    
    amtInput.addEventListener('keypress', function(e) {
        if (e.key === 'Enter') {
            CartManager.addBet();
        }
    });
}

const GameEngine = {
    validateEntry(type, num) {
        const cleanNum = num.toString().replace(/[-&]/g, '');
        const n = cleanNum;
        
        switch(type) {
            case 'borlette': return n.length === 2;
            case 'lotto3':   return n.length === 3;
            case 'lotto4':   return n.length === 4;
            case 'lotto5':   return n.length === 5;
            case 'mariage':  return n.length === 4;
            case 'auto_marriage': return true;
            case 'auto_lotto4': return true;
            case 'auto_lotto5': return true;
            case 'bo': return true;
            case 'grap': return true;
            default: 
                if (type.startsWith('n')) return true;
                return false;
        }
    },

    getCleanNumber(num) {
        return num.toString().replace(/[-&]/g, '');
    },

    generateAutoMarriageBets(amount) {
        const borletteNumbers = APP_STATE.currentCart
            .filter(item => item.game === 'borlette' && this.getCleanNumber(item.number).length === 2)
            .map(item => this.getCleanNumber(item.number));

        const uniqueNumbers = [...new Set(borletteNumbers)];
        const autoBets = [];
        
        for (let i = 0; i < uniqueNumbers.length; i++) {
            for (let j = i + 1; j < uniqueNumbers.length; j++) {
                autoBets.push({
                    id: Date.now() + Math.random(),
                    game: 'auto_marriage',
                    number: uniqueNumbers[i] + '&' + uniqueNumbers[j],
                    cleanNumber: uniqueNumbers[i] + uniqueNumbers[j],
                    amount: amount,
                    drawId: APP_STATE.selectedDraw,
                    timestamp: new Date().toISOString(),
                    isAutoGenerated: true
                });
            }
        }
        
        return autoBets;
    },

    generateAutoLotto4Bets(amount) {
        const borletteNumbers = APP_STATE.currentCart
            .filter(item => item.game === 'borlette' && this.getCleanNumber(item.number).length === 2)
            .map(item => this.getCleanNumber(item.number));

        const uniqueNumbers = [...new Set(borletteNumbers)];
        const autoBets = [];
        
        for (let i = 0; i < uniqueNumbers.length; i++) {
            for (let j = 0; j < uniqueNumbers.length; j++) {
                if (i !== j) {
                    autoBets.push({
                        id: Date.now() + Math.random(),
                        game: 'auto_lotto4',
                        number: uniqueNumbers[i] + '-' + uniqueNumbers[j],
                        cleanNumber: uniqueNumbers[i] + uniqueNumbers[j],
                        amount: amount,
                        drawId: APP_STATE.selectedDraw,
                        timestamp: new Date().toISOString(),
                        isAutoGenerated: true
                    });
                }
            }
        }
        
        return autoBets;
    },

    generateAutoLotto5Bets(amount) {
        const lotto3Numbers = APP_STATE.currentCart
            .filter(item => item.game === 'lotto3' && this.getCleanNumber(item.number).length === 3)
            .map(item => this.getCleanNumber(item.number));

        const uniqueNumbers = [...new Set(lotto3Numbers)];
        const autoBets = [];
        
        for (let i = 0; i < uniqueNumbers.length; i++) {
            for (let j = 0; j < uniqueNumbers.length; j++) {
                if (i !== j) {
                    autoBets.push({
                        id: Date.now() + Math.random(),
                        game: 'auto_lotto5',
                        number: uniqueNumbers[i] + '-' + uniqueNumbers[j].slice(-2),
                        cleanNumber: uniqueNumbers[i] + uniqueNumbers[j].slice(-2),
                        amount: amount,
                        drawId: APP_STATE.selectedDraw,
                        timestamp: new Date().toISOString(),
                        isAutoGenerated: true
                    });
                }
            }
        }
        
        return autoBets;
    },

    checkLotto3Win(bet, res) {
        const cleanNum = this.getCleanNumber(bet.number);
        const amt = bet.amount;
        
        let totalGain = 0;
        
        if (APP_STATE.lotto3Options[0]) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO3;
        }
        
        if (APP_STATE.lotto3Options[1] && cleanNum === res.lot2 + res.lot3) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO3;
        }
        
        if (APP_STATE.lotto3Options[2] && cleanNum === res.lot1.slice(-2) + res.lot2) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO3;
        }
        
        return totalGain;
    },

    checkLotto4Win(bet, res) {
        const cleanNum = this.getCleanNumber(bet.number);
        const amt = bet.amount;
        
        const b1 = res.lot1.slice(-2);
        const b2 = res.lot2;
        const b3 = res.lot3;
        
        let totalGain = 0;
        
        if (APP_STATE.lotto4Options[0] && cleanNum === (b2 + b3)) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO4;
        }
        
        if (APP_STATE.lotto4Options[1] && cleanNum === (b1 + b2)) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO4;
        }
        
        if (APP_STATE.lotto4Options[2] && cleanNum === (b1 + b3)) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO4;
        }
        
        return totalGain;
    },

    checkLotto5Win(bet, res) {
        const cleanNum = this.getCleanNumber(bet.number);
        const amt = bet.amount;
        
        const lot1 = res.lot1;
        const b2 = res.lot2;
        const b3 = res.lot3;
        const lastTwoOfLot1 = lot1.slice(-2);
        
        let totalGain = 0;
        
        if (APP_STATE.lotto5Options[0] && cleanNum === (lot1 + b2)) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO5;
        }
        
        if (APP_STATE.lotto5Options[1] && cleanNum === (lot1 + b3)) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO5;
        }
        
        if (APP_STATE.lotto5Options[2] && cleanNum === (lot1 + lastTwoOfLot1)) {
            totalGain += amt * CONFIG.GAMING_RULES.LOTTO5;
        }
        
        return totalGain;
    },

    checkWinningTicket(bet, res) {
        const cleanNum = this.getCleanNumber(bet.number);
        const amt = bet.amount;
        
        const b1 = res.lot1.slice(-2);
        const lot1 = res.lot1;
        const b2 = res.lot2;
        const b3 = res.lot3;

        switch(bet.game) {
            case 'borlette':
                if (cleanNum === b1) return amt * CONFIG.GAMING_RULES.BORLETTE.lot1;
                if (cleanNum === b2) return amt * CONFIG.GAMING_RULES.BORLETTE.lot2;
                if (cleanNum === b3) return amt * CONFIG.GAMING_RULES.BORLETTE.lot3;
                break;

            case 'lotto3':
                return this.checkLotto3Win(bet, res);

            case 'lotto4':
                return this.checkLotto4Win(bet, res);

            case 'lotto5':
                return this.checkLotto5Win(bet, res);

            case 'mariage':
                const p1 = cleanNum.slice(0, 2);
                const p2 = cleanNum.slice(2, 4);
                const lots = [b1, b2, b3];
                if (lots.includes(p1) && lots.includes(p2)) {
                    return amt * CONFIG.GAMING_RULES.MARIAGE;
                }
                break;

            case 'auto_marriage':
                return this.calculateAutoMarriageGain(bet, res);

            case 'auto_lotto4':
                return this.calculateAutoLotto4Gain(bet, res);

            case 'auto_lotto5':
                return this.calculateAutoLotto5Gain(bet, res);
        }
        return 0;
    },

    calculateAutoMarriageGain(bet, res) {
        const numbers = this.getCleanNumber(bet.number);
        const num1 = numbers.slice(0, 2);
        const num2 = numbers.slice(2, 4);
        
        const b1 = res.lot1.slice(-2);
        const b2 = res.lot2;
        const b3 = res.lot3;
        const winningNumbers = [b1, b2, b3];

        if (winningNumbers.includes(num1) && winningNumbers.includes(num2)) {
            return bet.amount * CONFIG.GAMING_RULES.AUTO_MARRIAGE;
        }
        return 0;
    },

    calculateAutoLotto4Gain(bet, res) {
        const numbers = this.getCleanNumber(bet.number);
        
        const b1 = res.lot1.slice(-2);
        const b2 = res.lot2;
        const b3 = res.lot3;
        
        let totalGain = 0;
        
        if (APP_STATE.lotto4Options[0] && numbers === (b2 + b3)) {
            totalGain += bet.amount * CONFIG.GAMING_RULES.AUTO_LOTTO4;
        }
        if (APP_STATE.lotto4Options[1] && numbers === (b1 + b2)) {
            totalGain += bet.amount * CONFIG.GAMING_RULES.AUTO_LOTTO4;
        }
        if (APP_STATE.lotto4Options[2] && numbers === (b1 + b3)) {
            totalGain += bet.amount * CONFIG.GAMING_RULES.AUTO_LOTTO4;
        }
        
        return totalGain;
    },

    calculateAutoLotto5Gain(bet, res) {
        const numbers = this.getCleanNumber(bet.number);
        
        const lot1 = res.lot1;
        const b2 = res.lot2;
        const b3 = res.lot3;
        const lastTwoOfLot1 = lot1.slice(-2);
        
        let totalGain = 0;
        
        if (APP_STATE.lotto5Options[0] && numbers === (lot1 + b2)) {
            totalGain += bet.amount * CONFIG.GAMING_RULES.AUTO_LOTTO5;
        }
        if (APP_STATE.lotto5Options[1] && numbers === (lot1 + b3)) {
            totalGain += bet.amount * CONFIG.GAMING_RULES.AUTO_LOTTO5;
        }
        if (APP_STATE.lotto5Options[2] && numbers === (lot1 + lastTwoOfLot1)) {
            totalGain += bet.amount * CONFIG.GAMING_RULES.AUTO_LOTTO5;
        }
        
        return totalGain;
    }
};

function switchTab(tabName) {
    APP_STATE.currentTab = tabName;
    
    document.querySelectorAll('.screen').forEach(screen => {
        screen.classList.remove('active');
    });
    
    document.querySelectorAll('.nav-item').forEach(nav => {
        nav.classList.remove('active');
    });
    
    let screenId = '';
    switch(tabName) {
        case 'home':
            screenId = 'draw-selection-screen';
            document.querySelector('.nav-item:nth-child(1)').classList.add('active');
            break;
        case 'history':
            screenId = 'history-screen';
            document.querySelector('.nav-item:nth-child(2)').classList.add('active');
            renderHistory();
            break;
        case 'reports':
            screenId = 'reports-screen';
            document.querySelector('.nav-item:nth-child(3)').classList.add('active');
            renderReports();
            break;
    }
    
    if (screenId) {
        document.getElementById(screenId).classList.add('active');
    }
}

function renderHistory() {
    const container = document.getElementById('history-container');
    
    if (APP_STATE.ticketsHistory.length === 0) {
        container.innerHTML = '<div class="empty-msg">Pa gen tikè nan istorik</div>';
        return;
    }
    
    container.innerHTML = APP_STATE.ticketsHistory.map(ticket => {
        let status = '';
        let statusClass = '';
        
        if (ticket.checked) {
            const totalBet = ticket.bets.reduce((sum, bet) => sum + bet.amount, 0);
            const hasWin = ticket.bets.some(bet => bet.gain > 0);
            
            if (hasWin) {
                status = 'GANYEN';
                statusClass = 'badge-win';
            } else {
                status = 'PÈDI';
                statusClass = 'badge-lost';
            }
        } else {
            status = 'AP TANN';
            statusClass = 'badge-wait';
        }
        
        return `
            <div class="history-card">
                <div class="card-header">
                    <span>#${ticket.id}</span>
                    <span>${ticket.date}</span>
                </div>
                <div>
                    <p><strong>Tiraj:</strong> ${ticket.drawName}</p>
                    <p><strong>Total:</strong> ${ticket.total} Gdes</p>
                    <p><strong>Nimewo:</strong> ${ticket.bets.length}</p>
                </div>
                <div class="card-footer">
                    <span class="badge ${statusClass}">${status}</span>
                    <button class="btn-small" onclick="viewTicketDetails(${ticket.id})">
                        <i class="fas fa-eye"></i> Detay
                    </button>
                </div>
            </div>
        `;
    }).join('');
}

function renderReports() {
    const totalTickets = APP_STATE.ticketsHistory.length;
    const totalBets = APP_STATE.ticketsHistory.reduce((sum, ticket) => sum + ticket.total, 0);
    
    const totalWins = APP_STATE.ticketsHistory.reduce((sum, ticket) => {
        if (ticket.checked && ticket.bets) {
            const ticketWins = ticket.bets.reduce((tSum, bet) => tSum + (bet.gain || 0), 0);
            return sum + ticketWins;
        }
        return sum;
    }, 0);
    
    const totalLoss = totalBets - totalWins;
    const balance = totalWins - totalBets;
    
    document.getElementById('total-tickets').textContent = totalTickets;
    document.getElementById('total-bets').textContent = totalBets + ' Gdes';
    document.getElementById('total-wins').textContent = totalWins + ' Gdes';
    document.getElementById('total-loss').textContent = totalLoss + ' Gdes';
    document.getElementById('balance').textContent = balance + ' Gdes';
    document.getElementById('balance').style.color = balance >= 0 ? 'var(--success)' : 'var(--danger)';
    
    const gameBreakdown = {};
    APP_STATE.ticketsHistory.forEach(ticket => {
        ticket.bets.forEach(bet => {
            const game = bet.game;
            if (!gameBreakdown[game]) {
                gameBreakdown[game] = { count: 0, amount: 0 };
            }
            gameBreakdown[game].count++;
            gameBreakdown[game].amount += bet.amount;
        });
    });
    
    const breakdownContainer = document.getElementById('game-breakdown');
    breakdownContainer.innerHTML = Object.entries(gameBreakdown).map(([game, data]) => `
        <div class="report-row">
            <span>${game.toUpperCase()}:</span>
            <span class="val">${data.count} jwèt (${data.amount} Gdes)</span>
        </div>
    `).join('');
}

function viewTicketDetails(ticketId) {
    const ticket = APP_STATE.ticketsHistory.find(t => t.id === ticketId);
    if (!ticket) return;
    
    let details = `
        <h3>Detay Tikè #${ticket.id}</h3>
        <p><strong>Tiraj:</strong> ${ticket.drawName}</p>
        <p><strong>Dat:</strong> ${ticket.date}</p>
        <p><strong>Total:</strong> ${ticket.total} Gdes</p>
        <hr>
        <h4>Paray yo:</h4>
    `;
    
    ticket.bets.forEach(bet => {
        let gameName = bet.game.toUpperCase();
        if (bet.specialType) gameName = bet.specialType;
        details += `<p>${gameName} ${bet.number} - ${bet.amount} Gdes ${bet.gain ? `(Ganyen: ${bet.gain} Gdes)` : ''}</p>`;
    });
    
    alert(details);
}

function toggleMultiDrawMode() {
    APP_STATE.multiDrawMode = !APP_STATE.multiDrawMode;
    const btn = document.getElementById('multi-draw-btn');
    const multiContainer = document.getElementById('multi-draw-container');
    const continueBtn = document.getElementById('multi-draw-continue');
    const drawGrid = document.getElementById('draws-container');
    
    if (APP_STATE.multiDrawMode) {
        btn.innerHTML = '<i class="fas fa-times"></i> Sispann Plizyè Tiraj';
        btn.style.background = 'rgba(255, 77, 77, 0.2)';
        btn.style.borderColor = 'var(--danger)';
        btn.style.color = 'var(--danger)';
        multiContainer.style.display = 'flex';
        continueBtn.style.display = 'block';
        drawGrid.style.display = 'none';
        renderMultiDrawSelector();
    } else {
        btn.innerHTML = '<i class="fas fa-layer-group"></i> Plizyè Tiraj';
        btn.style.background = 'rgba(0, 212, 255, 0.2)';
        btn.style.borderColor = 'var(--secondary)';
        btn.style.color = 'var(--secondary)';
        multiContainer.style.display = 'none';
        continueBtn.style.display = 'none';
        drawGrid.style.display = 'grid';
    }
}

function renderMultiDrawSelector() {
    const container = document.getElementById('multi-draw-container');
    container.innerHTML = CONFIG.DRAWS.map(draw => `
        <input type="checkbox" class="multi-draw-checkbox" id="multi-${draw.id}" 
               value="${draw.id}" ${APP_STATE.selectedDraws.includes(draw.id) ? 'checked' : ''}
               onchange="toggleMultiDrawSelection('${draw.id}')">
        <label for="multi-${draw.id}" class="multi-draw-label" style="border-left: 3px solid ${draw.color}">
            ${draw.name}
        </label>
    `).join('');
}

function toggleMultiDrawSelection(drawId) {
    const checkbox = document.getElementById(`multi-${drawId}`);
    if (checkbox.checked) {
        if (!APP_STATE.selectedDraws.includes(drawId)) {
            APP_STATE.selectedDraws.push(drawId);
        }
    } else {
        APP_STATE.selectedDraws = APP_STATE.selectedDraws.filter(id => id !== drawId);
    }
    
    document.getElementById('selected-draws-count').textContent = APP_STATE.selectedDraws.length;
}

function continueToBettingWithMultiDraw() {
    if (APP_STATE.selectedDraws.length === 0) {
        alert("Tanpri chwazi omwen yon tiraj");
        return;
    }
    
    APP_STATE.selectedDraw = APP_STATE.selectedDraws[0];
    const draw = CONFIG.DRAWS.find(d => d.id === APP_STATE.selectedDraw);
    document.getElementById('current-draw-title').textContent = draw.name;
    
    const indicator = document.getElementById('multi-draw-indicator');
    indicator.style.display = 'block';
    document.getElementById('selected-draws-count').textContent = APP_STATE.selectedDraws.length;
    
    document.getElementById('draw-selection-screen').classList.remove('active');
    document.getElementById('betting-screen').classList.add('active');
    document.querySelector('.back-button').style.display = 'flex';
    
    updateGameSelector();
}

function updateClock() {
    const now = new Date();
    document.getElementById('live-clock').innerText = now.toLocaleTimeString('fr-FR');
}

function renderDraws() {
    const container = document.getElementById('draws-container');
    container.innerHTML = CONFIG.DRAWS.map(draw => `
        <div class="draw-card ${APP_STATE.selectedDraw === draw.id ? 'active' : ''}" 
             onclick="selectDraw('${draw.id}')" 
             style="--draw-color: ${draw.color}">
            <span class="draw-name">${draw.name}</span>
            <span class="draw-time"><i class="far fa-clock"></i> ${draw.time}</span>
        </div>
    `).join('');
}

function selectDraw(id) {
    if (APP_STATE.multiDrawMode) return;
    
    APP_STATE.selectedDraw = id;
    APP_STATE.selectedDraws = [id];
    const draw = CONFIG.DRAWS.find(d => d.id === id);
    document.getElementById('current-draw-title').textContent = draw.name;
    
    document.getElementById('multi-draw-indicator').style.display = 'none';
    
    document.getElementById('draw-selection-screen').classList.remove('active');
    document.getElementById('betting-screen').classList.add('active');
    document.querySelector('.back-button').style.display = 'flex';
    
    updateGameSelector();
}

function goBackToDraws() {
    document.getElementById('betting-screen').classList.remove('active');
    document.getElementById('draw-selection-screen').classList.add('active');
    document.querySelector('.back-button').style.display = 'none';
    
    APP_STATE.multiDrawMode = false;
    const btn = document.getElementById('multi-draw-btn');
    btn.innerHTML = '<i class="fas fa-layer-group"></i> Plizyè Tiraj';
    btn.style.background = 'rgba(0, 212, 255, 0.2)';
    btn.style.borderColor = 'var(--secondary)';
    btn.style.color = 'var(--secondary)';
    
    document.getElementById('multi-draw-container').style.display = 'none';
    document.getElementById('multi-draw-continue').style.display = 'none';
    document.getElementById('draws-container').style.display = 'grid';
    
    renderDraws();
}

function toggleNumericChips() {
    APP_STATE.showNumericChips = !APP_STATE.showNumericChips;
    const container = document.getElementById('numeric-chips');
    const btn = document.getElementById('toggle-nx-btn');
    
    if (APP_STATE.showNumericChips) {
        container.classList.add('visible');
        btn.classList.add('active');
        btn.innerHTML = '<i class="fas fa-times"></i> NX';
    } else {
        container.classList.remove('visible');
        btn.classList.remove('active');
        btn.innerHTML = 'NX';
    }
    
    APP_STATE.showLottoGames = false;
    APP_STATE.showSpecialGames = false;
    document.getElementById('lotto-games').classList.remove('visible');
    document.getElementById('special-games').classList.remove('visible');
    
    document.querySelectorAll('#game-types .chip').forEach(chip => {
        chip.classList.remove('active');
    });
    document.querySelector('#game-types .chip[data-game="borlette"]').classList.add('active');
}

function toggleLottoOption(gameType, optionIndex) {
    let optionsArray;
    if (gameType === 3) {
        optionsArray = APP_STATE.lotto3Options;
    } else if (gameType === 4) {
        optionsArray = APP_STATE.lotto4Options;
    } else if (gameType === 5) {
        optionsArray = APP_STATE.lotto5Options;
    }
    
    optionsArray[optionIndex - 1] = !optionsArray[optionIndex - 1];
    
    const optionChip = document.querySelector(`#lotto${gameType}-options .option-chip[data-option="${optionIndex}"]`);
    if (optionChip) {
        optionChip.classList.toggle('active');
        optionChip.classList.add('animate-bounce');
        setTimeout(() => {
            optionChip.classList.remove('animate-bounce');
        }, 500);
    }
}

function selectGame(game) {
    APP_STATE.selectedGame = game;
    const input = document.getElementById('num-input');
    
    document.querySelectorAll('.chip').forEach(b => b.classList.remove('active'));
    document.querySelectorAll('.sub-game-btn').forEach(b => b.classList.remove('active'));
    
    if (game.startsWith('n')) {
        document.querySelector(`.numeric-chip[data-game="${game}"]`).classList.add('active');
    }
    
    document.querySelector('#game-types .chip[data-game="borlette"]').classList.add('active');
    
    const placeholderMap = {
        'borlette': '00',
        'lotto3': '000',
        'lotto4': '0000',
        'lotto5': '00000',
        'mariage': '0000',
        'auto_marriage': 'Auto',
        'auto_lotto4': 'Auto',
        'auto_lotto5': 'Auto',
        'bo': 'Auto',
        'grap': 'Auto'
    };
    
    input.placeholder = placeholderMap[game] || '00';
    
    if (game.includes('auto') || game === 'bo' || game === 'grap' || game.startsWith('n')) {
        input.disabled = true;
        input.value = '';
        input.placeholder = 'Auto-genere';
    } else {
        input.disabled = false;
        input.focus();
    }
    
    const lotto3Options = document.getElementById('lotto3-options');
    const lotto4Options = document.getElementById('lotto4-options');
    const lotto5Options = document.getElementById('lotto5-options');
    
    lotto3Options.classList.remove('visible');
    lotto4Options.classList.remove('visible');
    lotto5Options.classList.remove('visible');
    
    if (game === 'lotto3') {
        lotto3Options.classList.add('visible');
    } else if (game === 'lotto4' || game === 'auto_lotto4') {
        lotto4Options.classList.add('visible');
    } else if (game === 'lotto5' || game === 'auto_lotto5') {
        lotto5Options.classList.add('visible');
    }
}

function updateGameSelector() {
    const gameSelector = document.getElementById('game-types');
    gameSelector.innerHTML = `
        <button class="chip active" data-game="borlette" onclick="selectMainGame('borlette')">Borlette</button>
        <button class="chip" data-game="lotto" onclick="selectMainGame('lotto')">Lotto</button>
        <button class="chip" data-game="special" onclick="selectMainGame('special')">Jeux Spéciaux</button>
        <button class="chip" id="toggle-nx-btn" onclick="toggleNumericChips()">NX</button>
    `;
    
    document.querySelectorAll('.sub-game-btn').forEach(btn => {
        btn.addEventListener('click', function() {
            const game = this.getAttribute('onclick').match(/selectGame\('(\w+)'\)/)[1];
            selectGame(game);
            this.classList.add('active');
        });
    });
    
    selectGame('borlette');
}

function selectMainGame(game) {
    APP_STATE.showNumericChips = false;
    document.getElementById('numeric-chips').classList.remove('visible');
    document.getElementById('toggle-nx-btn').classList.remove('active');
    document.getElementById('toggle-nx-btn').innerHTML = 'NX';
    
    document.querySelectorAll('#game-types .chip').forEach(chip => {
        chip.classList.remove('active');
    });
    document.querySelector(`#game-types .chip[data-game="${game}"]`).classList.add('active');
    
    if (game === 'lotto') {
        APP_STATE.showLottoGames = !APP_STATE.showLottoGames;
        APP_STATE.showSpecialGames = false;
        
        if (APP_STATE.showLottoGames) {
            document.getElementById('lotto-games').classList.add('visible');
            document.getElementById('special-games').classList.remove('visible');
        } else {
            document.getElementById('lotto-games').classList.remove('visible');
        }
    } else if (game === 'special') {
        APP_STATE.showSpecialGames = !APP_STATE.showSpecialGames;
        APP_STATE.showLottoGames = false;
        
        if (APP_STATE.showSpecialGames) {
            document.getElementById('special-games').classList.add('visible');
            document.getElementById('lotto-games').classList.remove('visible');
        } else {
            document.getElementById('special-games').classList.remove('visible');
        }
    } else if (game === 'borlette') {
        APP_STATE.showLottoGames = false;
        APP_STATE.showSpecialGames = false;
        document.getElementById('lotto-games').classList.remove('visible');
        document.getElementById('special-games').classList.remove('visible');
        selectGame('borlette');
    }
}

const CartManager = {
    addBet() {
        const numInput = document.getElementById('num-input');
        const amtInput = document.getElementById('amt-input');
        let num = numInput.value.trim();
        const amt = parseFloat(amtInput.value);

        if (isNaN(amt) || amt <= 0) {
            alert("Tanpri antre yon montan ki valid");
            return;
        }

        if (APP_STATE.selectedGame === 'bo') {
            const boBets = SpecialGames.generateBOBets(amt);
            
            if (boBets.length === 0) {
                alert("Pa gen boules paires pou ajoute");
                return;
            }

            const draws = APP_STATE.multiDrawMode ? APP_STATE.selectedDraws : [APP_STATE.selectedDraw];
            
            draws.forEach(drawId => {
                boBets.forEach(bet => {
                    const newBet = {
                        ...bet,
                        id: Date.now() + Math.random(),
                        drawId: drawId,
                        drawName: CONFIG.DRAWS.find(d => d.id === drawId).name
                    };
                    APP_STATE.currentCart.push(newBet);
                });
            });
            
            this.renderCart();
            amtInput.value = '';
            alert(`${boBets.length * draws.length} boules paires ajoute nan panye`);
            return;
        }

        if (APP_STATE.selectedGame.startsWith('n')) {
            const digit = parseInt(APP_STATE.selectedGame[1]);
            const nBets = SpecialGames.generateNBets(digit, amt);
            
            if (nBets.length === 0) {
                alert("Pa gen boules pou ajoute");
                return;
            }

            const draws = APP_STATE.multiDrawMode ? APP_STATE.selectedDraws : [APP_STATE.selectedDraw];
            
            draws.forEach(drawId => {
                nBets.forEach(bet => {
                    const newBet = {
                        ...bet,
                        id: Date.now() + Math.random(),
                        drawId: drawId,
                        drawName: CONFIG.DRAWS.find(d => d.id === drawId).name
                    };
                    APP_STATE.currentCart.push(newBet);
                });
            });
            
            this.renderCart();
            amtInput.value = '';
            alert(`${nBets.length * draws.length} boules (N${digit}) ajoute nan panye`);
            return;
        }

        if (APP_STATE.selectedGame === 'grap') {
            const grapBets = SpecialGames.generateGRAPBets(amt);
            
            if (grapBets.length === 0) {
                alert("Pa gen boules grap pou ajoute");
                return;
            }

            const draws = APP_STATE.multiDrawMode ? APP_STATE.selectedDraws : [APP_STATE.selectedDraw];
            
            draws.forEach(drawId => {
                grapBets.forEach(bet => {
                    const newBet = {
                        ...bet,
                        id: Date.now() + Math.random(),
                        drawId: drawId,
                        drawName: CONFIG.DRAWS.find(d => d.id === drawId).name
                    };
                    APP_STATE.currentCart.push(newBet);
                });
            });
            
            this.renderCart();
            amtInput.value = '';
            alert(`${grapBets.length * draws.length} boules grap ajoute nan panye`);
            return;
        }

        if (APP_STATE.selectedGame.includes('auto')) {
            if (isNaN(amt) || amt <= 0) {
                alert("Tanpri antre yon montan ki valid");
                return;
            }

            let autoBets = [];
            if (APP_STATE.selectedGame === 'auto_marriage') {
                autoBets = GameEngine.generateAutoMarriageBets(amt);
            } else if (APP_STATE.selectedGame === 'auto_lotto4') {
                autoBets = GameEngine.generateAutoLotto4Bets(amt);
            } else if (APP_STATE.selectedGame === 'auto_lotto5') {
                autoBets = GameEngine.generateAutoLotto5Bets(amt);
            }
            
            if (autoBets.length === 0) {
                alert("Pa gen nimewo nan panye pou kreye jwèt otomatik yo");
                return;
            }

            const draws = APP_STATE.multiDrawMode ? APP_STATE.selectedDraws : [APP_STATE.selectedDraw];
            
            draws.forEach(drawId => {
                autoBets.forEach(bet => {
                    const newBet = {
                        ...bet,
                        id: Date.now() + Math.random(),
                        drawId: drawId,
                        drawName: CONFIG.DRAWS.find(d => d.id === drawId).name
                    };
                    APP_STATE.currentCart.push(newBet);
                });
            });
            
            this.renderCart();
            amtInput.value = '';
            alert(`${autoBets.length * draws.length} jwèt otomatik ajoute nan panye`);
            return;
        }

        if (!GameEngine.validateEntry(APP_STATE.selectedGame, num)) {
            alert("Nimewo sa pa bon pou " + APP_STATE.selectedGame);
            return;
        }

        num = GameEngine.getCleanNumber(num);
        
        let displayNum = num;
        if (APP_STATE.selectedGame === 'lotto4' && num.length === 4) {
            displayNum = num.slice(0, 2) + '-' + num.slice(2, 4);
        } else if (APP_STATE.selectedGame === 'lotto5' && num.length === 5) {
            displayNum = num.slice(0, 3) + '-' + num.slice(3, 5);
        } else if (APP_STATE.selectedGame === 'mariage' && num.length === 4) {
            displayNum = num.slice(0, 2) + '&' + num.slice(2, 4);
        }

        const draws = APP_STATE.multiDrawMode ? APP_STATE.selectedDraws : [APP_STATE.selectedDraw];
        
        draws.forEach(drawId => {
            const bet = {
                id: Date.now() + Math.random(),
                game: APP_STATE.selectedGame,
                number: displayNum,
                cleanNumber: num,
                amount: amt,
                drawId: drawId,
                drawName: CONFIG.DRAWS.find(d => d.id === drawId).name,
                timestamp: new Date().toISOString(),
                isAutoGenerated: false,
                isSpecial: false
            };

            APP_STATE.currentCart.push(bet);
        });
        
        this.renderCart();
        
        numInput.value = '';
        amtInput.value = '';
        numInput.focus();
    },

    removeBet(id) {
        APP_STATE.currentCart = APP_STATE.currentCart.filter(item => item.id !== id);
        this.renderCart();
    },

    renderCart() {
        const display = document.getElementById('cart-display');
        const summary = document.getElementById('cart-summary');
        const totalDisplay = document.getElementById('total-amount');
        const countDisplay = document.getElementById('items-count');

        if (APP_STATE.currentCart.length === 0) {
            display.innerHTML = '<div class="empty-msg">Pa gen paray ankò</div>';
            summary.style.display = 'none';
            countDisplay.innerText = "0 jwèt";
            return;
        }

        let total = 0;
        display.innerHTML = APP_STATE.currentCart.map(item => {
            total += item.amount;
            let gameName = '';
            
            if (item.isAutoGenerated && item.specialType) {
                gameName = item.specialType.toUpperCase();
            } else if (item.isAutoGenerated) {
                gameName = `${item.game.replace('_', ' ').toUpperCase()}*`;
            } else {
                gameName = item.game.toUpperCase();
            }
            
            const drawName = APP_STATE.multiDrawMode ? item.drawName : '';
            
            return `
                <div class="cart-item animate-fade">
                    <div class="item-info">
                        <span class="item-game">${gameName} ${item.number}</span>
                        ${APP_STATE.multiDrawMode ? `<span style="font-size:0.8rem; color:var(--text-dim)">${drawName}</span>` : ''}
                    </div>
                    <div class="item-price">
                        <span>${item.amount} ${CONFIG.CURRENCY}</span>
                        <button onclick="CartManager.removeBet(${item.id})" style="background:none; border:none; color:var(--danger); cursor:pointer;">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
            `;
        }).join('');

        totalDisplay.innerText = total;
        countDisplay.innerText = APP_STATE.currentCart.length + " jwèt";
        summary.style.display = 'block';
        
        display.scrollTop = display.scrollHeight;
    },

    saveTicketToHistory(ticket) {
        APP_STATE.ticketsHistory.unshift(ticket);
        if (APP_STATE.ticketsHistory.length > 100) APP_STATE.ticketsHistory.pop();
        localStorage.setItem('lotato_tickets', JSON.stringify(APP_STATE.ticketsHistory));
    }
};

const SyncManager = {
    isSyncing: false,

    async checkResults() {
        if (this.isSyncing) return;
        this.isSyncing = true;
        this.updateStatusUI('syncing', 'Checking server...');

        try {
            const response = await this.mockServerFetch();
            
            if (response && response.hasNewData) {
                APP_STATE.lastResults = response.results;
                this.updateStatusUI('success', 'Résultats à jour');
                WinnerEngine.verifyAllTickets(response.results);
            } else {
                this.updateStatusUI('online', 'Connecté au serveur');
            }
        } catch (error) {
            console.error("Sync Error:", error);
            this.updateStatusUI('error', 'Erreur de connexion');
        } finally {
            this.isSyncing = false;
        }
    },

    updateStatusUI(state, message) {
        const bar = document.getElementById('sync-status-bar');
        const text = document.getElementById('sync-text');
        
        bar.className = 'sync-' + state;
        text.innerText = message;
        
        if (state === 'error') {
            bar.style.background = 'var(--danger)';
        } else if (state === 'success') {
            bar.style.background = 'var(--success)';
            setTimeout(() => this.updateStatusUI('online', 'Connecté'), 3000);
        } else {
            bar.style.background = 'rgba(255,255,255,0.1)';
        }
    },

    mockServerFetch() {
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    hasNewData: true,
                    results: {
                        drawId: 'flo_matin',
                        lot1: "123",
                        lot2: "45",
                        lot3: "78",
                        date: new Date().toLocaleDateString()
                    }
                });
            }, 2000);
        });
    }
};

const WinnerEngine = {
    verifyAllTickets(results) {
        console.log("Vérification des tickets pour le tirage:", results.drawId);
        
        let winnersFound = [];

        APP_STATE.ticketsHistory.forEach(ticket => {
            if (ticket.drawId === results.drawId && !ticket.checked) {
                let ticketTotalGain = 0;
                let winningBets = [];

                ticket.bets.forEach(bet => {
                    const gain = GameEngine.checkWinningTicket(bet, results);
                    if (gain > 0) {
                        ticketTotalGain += gain;
                        winningBets.push({...bet, gain});
                    }
                });

                if (ticketTotalGain > 0) {
                    winnersFound.push({
                        ticketId: ticket.id,
                        totalGain: ticketTotalGain,
                        details: winningBets
                    });
                }
                ticket.checked = true;
            }
        });

        if (winnersFound.length > 0) {
            this.showWinnerNotification(winnersFound);
            localStorage.setItem('lotato_tickets', JSON.stringify(APP_STATE.ticketsHistory));
        }
    },

    showWinnerNotification(winners) {
        const modal = document.getElementById('winner-overlay');
        const detailsDiv = document.getElementById('winner-details');
        
        let html = winners.map(w => `
            <div class="winner-row">
                <p>Ticket: <b>#${w.ticketId.toString().slice(-6)}</b></p>
                <h3 style="color:var(--success)">Ganyen: ${w.totalGain} Gdes</h3>
            </div>
        `).join('<hr>');

        detailsDiv.innerHTML = html;
        modal.style.display = 'flex';
        
        this.playWinSound();
    },

    playWinSound() {
        const audio = new Audio('https://assets.mixkit.co/active_storage/sfx/2013/2013-preview.mp3');
        audio.play().catch(e => console.log("Audio play blocked"));
    }
};

function closeWinnerModal() {
    document.getElementById('winner-overlay').style.display = 'none';
}

async function processFinalTicket() {
    if (APP_STATE.currentCart.length === 0) {
        alert("Pa gen anyen nan panye an!");
        return;
    }

    const betsByDraw = {};
    APP_STATE.currentCart.forEach(bet => {
        if (!betsByDraw[bet.drawId]) {
            betsByDraw[bet.drawId] = [];
        }
        betsByDraw[bet.drawId].push(bet);
    });

    const drawIds = Object.keys(betsByDraw);
    let tickets = [];
    
    for (const drawId of drawIds) {
        const drawBets = betsByDraw[drawId];
        const draw = CONFIG.DRAWS.find(d => d.id === drawId);
        
        const ticket = {
            id: Math.floor(100000 + Math.random() * 900000),
            agent: "Agent-01",
            drawId: drawId,
            drawName: draw.name,
            bets: drawBets,
            total: drawBets.reduce((sum, b) => sum + b.amount, 0),
            date: new Date().toLocaleString('fr-FR'),
            checked: false
        };

        tickets.push(ticket);
        
        try {
            await sendTicketToServer(ticket);
            CartManager.saveTicketToHistory(ticket);
        } catch (error) {
            console.error("Erreur sauvegarde:", error);
            alert("Gen yon pwoblèm koneksyon, men fich la sove nan memwa telefòn nan.");
            CartManager.saveTicketToHistory(ticket);
        }
    }
    
    tickets.forEach(ticket => {
        printThermalTicket(ticket);
    });
    
    APP_STATE.currentCart = [];
    CartManager.renderCart();
    
    if (tickets.length === 1) {
        alert("Fich sove ak siksè! #" + tickets[0].id);
    } else {
        alert(`${tickets.length} fich sove ak siksè!`);
    }
}

function printThermalTicket(ticket) {
    const printWindow = window.open('', '_blank', 'width=300,height=600');
    
    let betsHtml = ticket.bets.map(b => {
        let gameName = '';
        if (b.isAutoGenerated && b.specialType) {
            gameName = b.specialType.toUpperCase();
        } else if (b.isAutoGenerated) {
            gameName = `${b.game.replace('_', ' ').toUpperCase()}*`;
        } else {
            gameName = b.game.toUpperCase();
        }
        
        return `
            <div style="display:flex; justify-content:space-between; font-size:14px;">
                <span>${gameName} ${b.number}</span>
                <span>${b.amount}G</span>
            </div>
        `;
    }).join('');

    const content = `
        <html>
        <body style="font-family:'Courier New', monospace; width:100%; padding:0; margin:0; text-align:center;">
            <h2 style="margin-bottom:5px;">LOTATO PRO</h2>
            <p style="font-size:12px; margin:0;">Nouvelle Version 2024</p>
            <p style="font-size:12px;">--------------------------</p>
            <p style="font-size:14px; font-weight:bold;">TIRAJ: ${ticket.drawName.toUpperCase()}</p>
            <p style="font-size:12px;">TICKET: #${ticket.id}</p>
            <p style="font-size:12px;">DATE: ${ticket.date}</p>
            <p style="font-size:12px;">--------------------------</p>
            <div style="text-align:left; padding:0 10px;">
                ${betsHtml}
            </div>
            <p style="font-size:12px;">--------------------------</p>
            <h3 style="margin-top:5px;">TOTAL: ${ticket.total} Gdes</h3>
            <p style="font-size:10px; margin-top:15px;">Mèci paske ou chwazi nou!</p>
            <p style="font-size:10px;">Bòn Chans!</p>
            <br><br>
        </body>
        </html>
    `;

    printWindow.document.write(content);
    printWindow.document.close();
    
    setTimeout(() => {
        printWindow.print();
        printWindow.close();
    }, 500);
}

async function sendTicketToServer(ticket) {
    console.log("Ticket envoyé au serveur:", ticket);
    return true; 
}

function initApp() {
    const savedConfig = JSON.parse(localStorage.getItem('lotato_config'));
    if(savedConfig) {
        CONFIG.SERVER_URL = savedConfig.url;
        APP_STATE.agentName = savedConfig.agent;
    }

    renderDraws();
    updateClock();
    setTimeout(() => SyncManager.checkResults(), 2000);
    console.log("LOTATO PRO Ready - Production Mode");

    setupInputAutoMove();
    
    document.getElementById('add-bet-btn').addEventListener('click', () => CartManager.addBet());
    
    updateGameSelector();
    
    // Initialiser les options de lotto pour refléter l'état par défaut
    document.querySelectorAll('#lotto3-options .option-chip').forEach((chip, index) => {
        chip.classList.toggle('active', APP_STATE.lotto3Options[index]);
        chip.querySelector('input').checked = APP_STATE.lotto3Options[index];
    });
    
    document.querySelectorAll('#lotto4-options .option-chip').forEach((chip, index) => {
        chip.classList.toggle('active', APP_STATE.lotto4Options[index]);
        chip.querySelector('input').checked = APP_STATE.lotto4Options[index];
    });
    
    document.querySelectorAll('#lotto5-options .option-chip').forEach((chip, index) => {
        chip.classList.toggle('active', APP_STATE.lotto5Options[index]);
        chip.querySelector('input').checked = APP_STATE.lotto5Options[index];
    });
}

document.addEventListener('DOMContentLoaded', initApp);
setInterval(updateClock, 1000);
setInterval(() => SyncManager.checkResults(), 120000);

if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/service-worker.js')
        .then(reg => console.log('PWA: Service Worker actif'))
        .catch(err => console.error('PWA: Erreur', err));
}